server:
  port: 8089
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.224.131.2:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: datac.com


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: null

  typeAliasesPackage: com.footlocer.mon.entity
  mapperLocations: classpath:mapper/*Mapper.xml



touch:
  username: xuzi
  password: sssd
  usd: 7.15
  #token user
  token1: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTc2ZjBhM2FiN2MyNDE4NTVjZGM0NTciLCJ1c2VybmFtZSI6IuiKnOa5liIsImlzQWRtaW4iOmZhbHNlLCJhdXRoIjp0cnVlLCJkaXNhYmxlZCI6ZmFsc2UsImlhdCI6MTcwODQ3MTMwMSwiZXhwIjoxNzExMDYzMzAxfQ.2tycd2REKWURzID9lXnnDDZbec_yA2QIZT5Srb25gN8
  user1: 6576f0a3ab7c241855cdc457